# This is a basic workflow to help you get started with Actions

name: CI for PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_and_unit_test:
    # The type of runner that the job will run on
    runs-on: R4-FNT-A-1-3-9

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Upload unit test report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: ci/SmokeTests/reports/html/report.html

      # Build docker image
      - name: Build Docker image
        run:  |
          docker build -t prayan-maas-micro-service-local .

      # Run docker image
      #- name: Run Docker image
      #  run:  |
      #    docker rm -f frontend-local
      #    docker run -d -p 3000:3000 --name prayan-maas-micro-service-local
      #    curl localhost:3000

      #Image Scan Using Trivy
      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --no-progress prayan-maas-micro-service-local:latest
          # Save the Trivy scan report to a file
          trivy image --no-progress --format json prayan-maas-micro-service-local:latest > trivy_report.json

      - name: Upload Trivy scan report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: trivy-reports
          path: trivy_report.json
